import type { Metadata } from "next";
import { RocknRoll_One } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";

import React from "react";
import ReactQueryProvider from "./ReactQueryProvider";
import SideBar from "@/components/side_bar/SideBar";
import Header from "@/components/header/Header";
// import { usePathname } from "next/navigation";

const inter = RocknRoll_One({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <AppRouterCacheProvider>
            <div className="flex flex-row max-w-screen max-h-screen bg-white">
              <SideBar />
              <div className="w-full h-screen flex flex-col">
                <Header />
                <main className="w-full h-full">{children}</main>
              </div>
            </div>
          </AppRouterCacheProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
